/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_l2fprod_gui_nativeskin_win32_Win32NativeSkin */

#ifndef _Included_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
#define _Included_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: theInstance */
/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    setWindowRegion0
 * Signature: (IJZ)V
 */
JNIEXPORT void JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_setWindowRegion0
  (JNIEnv *, jclass, jint, jlong, jboolean);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    getHWND0
 * Signature: (Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_getHWND0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    setWindowTransparency0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_setWindowTransparency0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    createEllipticRegion0
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_createEllipticRegion0
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    createRectangleRegion0
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_createRectangleRegion0
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    createRoundRectangleRegion0
 * Signature: (IIIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_createRoundRectangleRegion0
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    createPolygonRegion0
 * Signature: ([I[II)J
 */
JNIEXPORT jlong JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_createPolygonRegion0
  (JNIEnv *, jclass, jintArray, jintArray, jint);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    combineRegions0
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_combineRegions0
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    createRegion0
 * Signature: ([III)J
 */
JNIEXPORT jlong JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_createRegion0
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_l2fprod_gui_nativeskin_win32_Win32NativeSkin
 * Method:    setAlwaysOnTop0
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_l2fprod_gui_nativeskin_win32_Win32NativeSkin_setAlwaysOnTop0
  (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
