/* Generated By:JavaCC: Do not edit this line. GtkParserConstants.java */
/**
 * @PROJECT.FULLNAME@ @VERSION@ License.
 *
 * Copyright @YEAR@ L2FProd.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.l2fprod.gui.plaf.skin.impl.gtk.parser;

public interface GtkParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int DECIMAL_LITERAL = 13;
  int STRING_LITERAL = 14;
  int BOOLEAN = 15;
  int EXTRA = 16;
  int FONT = 17;
  int STYLE = 18;
  int CLASS = 19;
  int ENGINE = 20;
  int IMAGE = 21;
  int FUNCTION = 22;
  int RECOLORABLE = 23;
  int FILE = 24;
  int BORDER = 25;
  int STRETCH = 26;
  int SHADOW = 27;
  int STATE = 28;
  int DETAIL = 29;
  int GAP_SIDE = 30;
  int GAP_FILE = 31;
  int GAP_BORDER = 32;
  int GAP_START_FILE = 33;
  int GAP_START_BORDER = 34;
  int GAP_END_FILE = 35;
  int GAP_END_BORDER = 36;
  int OVERLAY_FILE = 37;
  int OVERLAY_BORDER = 38;
  int OVERLAY_STRETCH = 39;
  int ORIENTATION = 40;
  int ARROW_DIRECTION = 41;
  int FUNCTION_TYPE = 42;
  int STATE_TYPE = 43;
  int SHADOW_TYPE = 44;
  int ORIENTATION_TYPE = 45;
  int DIRECTION = 46;
  int LCROC = 47;
  int RCROC = 48;
  int LBRACK = 49;
  int RBRACK = 50;
  int ASSIGN = 51;
  int COMMA = 52;
  int OTHER_TOKEN = 53;
  int WIDGET_CLASS = 54;
  int WIDGET = 55;
  int PROPERTY_KEY = 56;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"#\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<DECIMAL_LITERAL>",
    "<STRING_LITERAL>",
    "<BOOLEAN>",
    "<EXTRA>",
    "\"font\"",
    "\"style\"",
    "\"class\"",
    "\"engine\"",
    "\"image\"",
    "\"function\"",
    "\"recolorable\"",
    "\"file\"",
    "\"border\"",
    "\"stretch\"",
    "\"shadow\"",
    "\"state\"",
    "\"detail\"",
    "\"gap_side\"",
    "\"gap_file\"",
    "\"gap_border\"",
    "\"gap_start_file\"",
    "\"gap_start_border\"",
    "\"gap_end_file\"",
    "\"gap_end_border\"",
    "\"overlay_file\"",
    "\"overlay_border\"",
    "\"overlay_stretch\"",
    "\"orientation\"",
    "\"arrow_direction\"",
    "<FUNCTION_TYPE>",
    "<STATE_TYPE>",
    "<SHADOW_TYPE>",
    "<ORIENTATION_TYPE>",
    "<DIRECTION>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\",\"",
    "<OTHER_TOKEN>",
    "\"widget_class\"",
    "\"widget\"",
    "<PROPERTY_KEY>",
  };

}
