/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_l2fprod_gui_nativeskin_x11_X11NativeSkin */

#ifndef _Included_com_l2fprod_gui_nativeskin_x11_X11NativeSkin
#define _Included_com_l2fprod_gui_nativeskin_x11_X11NativeSkin
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: theInstance */
/*
 * Class:     com_l2fprod_gui_nativeskin_x11_X11NativeSkin
 * Method:    setWindowRegion0
 * Signature: (II[III)V
 */
JNIEXPORT void JNICALL Java_com_l2fprod_gui_nativeskin_x11_X11NativeSkin_setWindowRegion0
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
